version: "1.0"
services:
  keycloak:
    image: jarnoweemen/auctionsense:keycloak-auctionsense
    container_name: keycloak
    ports:
      - "8484:8484"
    networks:
      - auctionsense_network

  postgres:
    image: jarnoweemen/auctionsense:postgres-auctionsense
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - auctionsense_network
      
  quarkus:
    image: jarnoweemen/auctionsense:quarkus-auctionsense
    container_name: quarkus
    ports:
      - "8080:8080"
    depends_on:
      - "keycloak"
      - "postgres"
    networks:
      - auctionsense_network
      
networks:
  auctionsense_network:
    driver: bridge